export const texte = {
  app: {
    name: 'Punkterfassung',
  },
  berichtsliste: {
    titel: 'Berichte',
    keineBerichte: 'Noch keine Berichte angelegt.',
    neuerBericht: 'Neuer Bericht',
    einstellungen: 'Einstellungen',
    punkteOffen: 'offen',
    punkteInBearbeitung: 'in Bearbeitung',
    punkteErledigt: 'erledigt',
  },
  berichtForm: {
    titelNeu: 'Neuer Bericht',
    titelBearbeiten: 'Bericht bearbeiten',
    projektNr: 'Projekt-Nr.',
    projektName: 'Projektname',
    vorgang: 'Vorgang',
    beschreibung: 'Beschreibung',
    ersteller: 'Ersteller',
    datum: 'Datum',
    neubauNr: 'Neubau-Nr.',
    neubauName: 'Neubau-Name',
    ort: 'Ort',
    speichern: 'Speichern',
    abbrechen: 'Abbrechen',
    pflichtfeldHinweis: 'Bitte alle Pflichtfelder ausfüllen.',
  },
  einstellungen: {
    titel: 'Einstellungen',
    ersteller: 'Ersteller',
    ersteller_hinweis: 'Vorgabe für neue Berichte.',
    baugruppen: 'Baugruppen',
    baugruppeNeu: 'Neue Baugruppe',
    hinzufuegen: 'Hinzufügen',
    aktiv: 'Aktiv',
    inaktiv: 'Inaktiv',
    zurueck: 'Zurück',
  },
  allgemein: {
    zurueck: 'Zurück',
    loeschen: 'Löschen',
    speichern: 'Speichern',
  },
  status: {
    offen: 'offen',
    in_bearbeitung: 'in Bearbeitung',
    erledigt: 'erledigt',
    geloescht: 'gelöscht',
  },
  punktForm: {
    titelNeu: 'Neuer Punkt',
    titelBearbeiten: 'Punkt bearbeiten',
    anlageNr: 'Anlagen-Nr.',
    lage: 'Lage',
    baugruppe: 'Baugruppe',
    baugruppeBitteWaehlen: '-- Baugruppe wählen --',
    anmerkung: 'Anmerkung',
    status: 'Status',
    speichernNaechster: 'Speichern & nächster Punkt',
    neueAnlage: 'Neue Anlage',
    speichern: 'Speichern',
    abbrechen: 'Abbrechen',
    loeschen: 'Löschen',
    fertig: 'Fertig',
    pflichtfeldHinweis: 'Bitte Anlagen-Nr., Lage und Baugruppe angeben.',
    loeschenBestaetigen: 'Diesen Punkt wirklich löschen?',
    loeschenGrundFrage: 'Grund (optional):',
  },
  berichtUebersicht: {
    zurueck: 'Zurück',
    bearbeiten: 'Bearbeiten',
    neuerPunkt: 'Neuer Punkt',
    abschliessen: 'Bericht abschließen',
    wiederEroeffnen: 'Wieder öffnen',
    filterAlle: 'Alle',
    filterOffen: 'Offen',
    filterInBearbeitung: 'In Bearbeitung',
    filterErledigt: 'Erledigt',
    filterGeloescht: 'Gelöscht',
    keinePunkte: 'Noch keine Punkte erfasst.',
    wiederherstellen: 'Wiederherstellen',
    fotos: 'Fotos',
  },
} as const;
