export const texte = {
  app: {
    name: 'Punkterfassung',
  },
  berichtsliste: {
    titel: 'Berichte',
    keineBerichte: 'Noch keine Berichte angelegt.',
    neuerBericht: 'Neuer Bericht',
    einstellungen: 'Einstellungen',
    punkteOffen: 'offen',
    punkteInBearbeitung: 'in Bearbeitung',
    punkteErledigt: 'erledigt',
  },
  berichtForm: {
    titelNeu: 'Neuer Bericht',
    titelBearbeiten: 'Bericht bearbeiten',
    projektNr: 'Projekt-Nr.',
    projektName: 'Projektname',
    vorgang: 'Vorgang',
    beschreibung: 'Beschreibung',
    ersteller: 'Ersteller',
    datum: 'Datum',
    neubauNr: 'Neubau-Nr.',
    neubauName: 'Neubau-Name',
    ort: 'Ort',
    speichern: 'Speichern',
    abbrechen: 'Abbrechen',
    pflichtfeldHinweis: 'Bitte alle Pflichtfelder ausfüllen.',
  },
  einstellungen: {
    titel: 'Einstellungen',
    ersteller: 'Ersteller',
    ersteller_hinweis: 'Vorgabe für neue Berichte.',
    baugruppen: 'Baugruppen',
    baugruppeNeu: 'Neue Baugruppe',
    hinzufuegen: 'Hinzufügen',
    aktiv: 'Aktiv',
    inaktiv: 'Inaktiv',
    zurueck: 'Zurück',
  },
  allgemein: {
    zurueck: 'Zurück',
    loeschen: 'Löschen',
    speichern: 'Speichern',
  },
} as const;
