export const texte = {
  app: {
    name: 'Punkterfassung',
  },
  berichtsliste: {
    titel: 'Berichte',
    keineBerichte: 'Noch keine Berichte angelegt.',
    neuerBericht: 'Neuer Bericht',
    einstellungen: 'Einstellungen',
    punkteOffen: 'offen',
    punkteInBearbeitung: 'in Bearbeitung',
    punkteErledigt: 'erledigt',
    zipImport: 'ZIP-Import',
    zipImportFehler: 'ZIP-Import fehlgeschlagen.',
    zipKollisionFrage: 'Ein Bericht mit dieser ID existiert bereits. Wie soll verfahren werden?',
    zipKollisionErsetzen: 'Ersetzen',
    zipKollisionKopie: 'Als Kopie importieren',
    abbrechen: 'Abbrechen',
    zipBackupHinweis: (tage: number) => `Seit ${tage} Tagen kein Backup`,
  },
  berichtForm: {
    titelNeu: 'Neuer Bericht',
    titelBearbeiten: 'Bericht bearbeiten',
    projektNr: 'Projekt-Nr.',
    projektName: 'Projektname',
    vorgang: 'Vorgang',
    beschreibung: 'Beschreibung',
    ersteller: 'Ersteller',
    datum: 'Datum',
    neubauNr: 'Neubau-Nr.',
    neubauName: 'Neubau-Name',
    ort: 'Ort',
    speichern: 'Speichern',
    abbrechen: 'Abbrechen',
    pflichtfeldHinweis: 'Bitte alle Pflichtfelder ausfüllen.',
  },
  einstellungen: {
    titel: 'Einstellungen',
    ersteller: 'Ersteller',
    ersteller_hinweis: 'Vorgabe für neue Berichte.',
    baugruppen: 'Baugruppen',
    baugruppeNeu: 'Neue Baugruppe',
    hinzufuegen: 'Hinzufügen',
    aktiv: 'Aktiv',
    inaktiv: 'Inaktiv',
    zurueck: 'Zurück',
    speicherTitel: 'Speicher & Datensicherheit',
    speicherPersistiertJa: 'Dauerhaft gesichert (persistent) – iOS räumt diese Daten nicht automatisch auf.',
    speicherPersistiertNein: 'Nicht als dauerhaft markiert – iOS kann diese Daten bei Speicherknappheit löschen.',
    speicherHinweis:
      'Alle Berichte liegen ausschließlich auf diesem Gerät. Wird das App-Symbol vom Home-Bildschirm entfernt oder werden die Website-Daten gelöscht, gehen sie unwiderruflich verloren. Wichtige Berichte regelmäßig als ZIP-Backup sichern.',
  },
  allgemein: {
    zurueck: 'Zurück',
    loeschen: 'Löschen',
    speichern: 'Speichern',
  },
  status: {
    offen: 'offen',
    in_bearbeitung: 'in Bearbeitung',
    erledigt: 'erledigt',
    geloescht: 'gelöscht',
  },
  punktForm: {
    titelNeu: 'Neuer Punkt',
    titelBearbeiten: 'Punkt bearbeiten',
    anlageNr: 'Anlagen-Nr.',
    lage: 'Lage',
    baugruppe: 'Baugruppe',
    baugruppeBitteWaehlen: '-- Baugruppe wählen --',
    fotos: 'Fotos',
    fotoAufnehmen: 'Foto',
    anmerkung: 'Anmerkung',
    status: 'Status',
    speichernNaechster: 'Speichern & nächster Punkt',
    neueAnlage: 'Neue Anlage',
    speichern: 'Speichern',
    abbrechen: 'Abbrechen',
    loeschen: 'Löschen',
    fertig: 'Fertig',
    pflichtfeldHinweis: 'Bitte Anlagen-Nr., Lage und Baugruppe angeben.',
    loeschenBestaetigen: 'Diesen Punkt wirklich löschen?',
    loeschenGrundFrage: 'Grund (optional):',
  },
  berichtUebersicht: {
    zurueck: 'Zurück',
    bearbeiten: 'Bearbeiten',
    neuerPunkt: 'Neuer Punkt',
    abschliessen: 'Bericht abschließen',
    wiederEroeffnen: 'Wieder öffnen',
    filterAlle: 'Alle',
    filterOffen: 'Offen',
    filterInBearbeitung: 'In Bearbeitung',
    filterErledigt: 'Erledigt',
    filterGeloescht: 'Gelöscht',
    keinePunkte: 'Noch keine Punkte erfasst.',
    wiederherstellen: 'Wiederherstellen',
    fotos: 'Fotos',
    export: 'Export',
    exportAuswahlFrage: 'Welche Punkte exportieren?',
    exportAlle: 'Alle Punkte',
    exportOffenBearbeitung: 'Nur offen + in Bearbeitung',
    exportExcel: 'Als Excel',
    exportPdf: 'Als PDF',
    exportZip: 'Als ZIP-Backup',
    exportZipHinweis: 'Das ZIP-Backup enthält immer alle Punkte, auch gelöschte.',
    exportLaeuft: 'Export läuft …',
    pdfVorschauTitel: 'PDF-Vorschau',
    pdfSchliessen: 'Schließen',
    pdfTeilen: 'Teilen / Speichern',
    pdfSeitenLaden: 'Weitere Seiten werden geladen …',
  },
} as const;
